### ISSUE TITLE
Most checks with c++ files fail with "Error while processing" (v0.3.3)

### ISSUE THREAD

**Issue by ruedbi** [dougpuob/cppnamelint#55] opened 2021-03-04 11:42 UTC
cppnamelint check ...
using default cppnamelint.toml

with -verbose and -logfile=... I get some more infos:
1) terminated by signal 11
2) log:
[123211][Main.cpp!LogConfig@232                      ] CheckSubcommand     = 1866688367
[123211][Main.cpp!LogConfig@233                      ] TestSubcommand      = 1866688367
[123211][Main.cpp!LogConfig@235                      ] bCheckFileName      = 1866688367
[123211][Main.cpp!LogConfig@236                      ] bCheckFunctionName  = 1866688367
[123211][Main.cpp!LogConfig@238                      ] bCheckEnum          = 1866688367
[123211][Main.cpp!LogConfig@239                      ] bCheckStruct        = 1866688367
[123211][Main.cpp!LogConfig@240                      ] bCheckVariableName  = 1866688367
[123211][Main.cpp!LogCheckResult@247                 ] Assert.nErrorOccurred = 1699900259
[123211][Main.cpp!LogCheckResult@248                 ] Assert.nInvalidDecl   = 1699900259
[123211][Main.cpp!LogCheckResult@249                 ] Assert.nNumWarnings   = 1699900259
[123211][Main.cpp!LogCheckResult@251                 ] Checked.nClass        = 1699900259
[123211][Main.cpp!LogCheckResult@252                 ] Checked.nEnum         = 1699900259
[123211][Main.cpp!LogCheckResult@253                 ] Checked.nFile         = 1699900259
[123211][Main.cpp!LogCheckResult@254                 ] Checked.nFunction     = 1699900259
[123211][Main.cpp!LogCheckResult@255                 ] Checked.nParameter    = 1699900259
[123211][Main.cpp!LogCheckResult@256                 ] Checked.nStruct       = 1699900259
[123211][Main.cpp!LogCheckResult@257                 ] Checked.nUnion        = 1699900259
[123211][Main.cpp!LogCheckResult@258                 ] Checked.nVariable     = 1699900259
[123211][Main.cpp!LogCheckResult@260                 ] Error.nClass          = 1699900259
[123211][Main.cpp!LogCheckResult@261                 ] Error.nEnum           = 1699900259
[123211][Main.cpp!LogCheckResult@262                 ] Error.nFile           = 1699900259
[123211][Main.cpp!LogCheckResult@263                 ] Error.nFunction       = 1699900259
[123211][Main.cpp!LogCheckResult@264                 ] Error.nParameter      = 1699900259
[123211][Main.cpp!LogCheckResult@265                 ] Error.nStruct         = 1699900259
[123211][Main.cpp!LogCheckResult@266                 ] Error.nUnion          = 1699900259
[123211][Main.cpp!LogCheckResult@267                 ] Error.nVariable       = 1699900259
[123211][Main.cpp!main@334                           ] Program is going to close. (iRet=1852399981)
[123450][Main.cpp!LogConfig@232                      ] CheckSubcommand     = 1866688367
[123450][Main.cpp!LogConfig@233                      ] TestSubcommand      = 1866688367
[123450][Main.cpp!LogConfig@235                      ] bCheckFileName      = 1866688367
[123450][Main.cpp!LogConfig@236                      ] bCheckFunctionName  = 1866688367
[123450][Main.cpp!LogConfig@238                      ] bCheckEnum          = 1866688367
[123450][Main.cpp!LogConfig@239                      ] bCheckStruct        = 1866688367
[123450][Main.cpp!LogConfig@240                      ] bCheckVariableName  = 1866688367

3) A success looks like so:
cppnamelint utility v0.3.3
---------------------------------------------------
clang version 8.0.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/user/bin/cppnamelint
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda, version 10.0
clang Invocation:
 "/home/user/bin/cppnamelint/clang-tool" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-fsyntax-only" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "measure_cmd_client.h" "-mrelocation-model" "static" "-mthread-model" "posix" "-mdisable-fp-elim" "-fmath-errno" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-fuse-init-array" "-target-cpu" "x86-64" "-dwarf-column-info" "-debugger-tuning=gdb" "-v" "-resource-dir" "/home/user/bin/cppnamelint/../lib/clang/8.0.0" "-internal-isystem" "/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0" "-internal-isystem" "/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/x86_64-linux-gnu/c++/7.5.0" "-internal-isystem" "/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/x86_64-linux-gnu/c++/7.5.0" "-internal-isystem" "/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/backward" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/home/user/bin/cppnamelint/../lib/clang/8.0.0/include" "-internal-externc-isystem" "/usr/include/x86_64-linux-gnu" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-fdeprecated-macro" "-fdebug-compilation-dir" "/home/user/projects/embedded-linux/apps/hr-radar/6455/apps/measure_cmd/client" "-ferror-limit" "19" "-fmessage-length" "177" "-fobjc-runtime=gcc" "-fcxx-exceptions" "-fexceptions" "-fdiagnostics-show-option" "-fcolor-diagnostics" "-x" "c++" "/home/user/projects/embedded-linux/apps/hr-radar/6455/apps/./measure_cmd/client/measure_cmd_client.h" "-faddrsig"

clang -cc1 version 8.0.0 based upon LLVM 8.0.0 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/home/user/bin/cppnamelint/../lib/clang/8.0.0/include"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/x86_64-linux-gnu/c++/7.5.0"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0
 /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/x86_64-linux-gnu/c++/7.5.0
 /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/backward
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
...

HTH

**Comment by ruedbi** [comment] 2021-03-05 07:47
looks like it fails here:
Common.cpp / 147:
  if (0 == Tool.run(NewFactory.get())) {

HTH

**Comment by dougpuob** [comment] 2021-03-08 03:13
Hi @ruedbi ,

Recently, I am trying to merge this major functions to `Clang-Tidy`, this https://reviews.llvm.org/D86671. Now it stuck in code review, if you need those functions, please leave a message there too, expressing you need the commit too.

Back to you original topic. If you need it too, can you please give me your code snippets?

**Comment by ruedbi** [comment] 2021-03-08 06:41
CaseType could be interesting, Hungarian notation not so much
what kind of message would help?

**Comment by ruedbi** [comment] 2021-03-08 06:42
Code snippets: You mean the code that causes the processing error?
That is not possible (commercial code), but maybe I find some public code to reproduce the issue.

**Comment by dougpuob** [comment] 2021-03-08 06:54
> Code snippets: You mean the code that causes the processing error?
> That is not possible (commercial code), but maybe I find some public code to reproduce the issue.

yep, I need it to reproduce.

Maybe you can have it a look to Clang-Tidy, `readability-identifier-naming` (https://clang.llvm.org/extra/clang-tidy/checks/readability-identifier-naming.html).

**Comment by ruedbi** [comment] 2021-03-08 08:47
I randomly selected a simple code repo from github: https://github.com/changkun/modern-cpp-tutorial
all .cpp files are failing with
cppnamelint check  -config cppnamelint.toml ...

**Comment by ruedbi** [comment] 2021-03-08 08:48
thanks for the hint to readability-identifier-naming, I will check that too

**Comment by dougpuob** [comment] 2021-03-27 15:41
Hi @ruedbi 
Sorry for replying you late. 

I have fixed the issue, can you have it a try with your project?
https://github.com/dougpuob/cppnamelint/releases/tag/untagged-990be7794a2930c5479c

If you are interested in the details, click here (https://github.com/dougpuob/cppnamelint/commit/ef537f938892baddf87a7c47ef3274b6ccafa3cb)

Another I told you is incorrect about building this project with newer llvm. I can built it with llvmorg-12.0.0-rc3. There are several issues I will try to improve later (made action items for them).
1. build with newer llvm version (with vcpkg on local and Azure CI/CD) #58
2. change the logger. #59 
3. follow-up this issue, why this issue cannot be duplicated on Windows version. #60

Anyway, thank for your report. Please let me know if the issue was fixed on your project, if fixed I will close this issue.

**Comment by ruedbi** [comment] 2021-03-29 06:59
Hi Douglas,

thanks for your bugfix, I highly appreciate that.
The tag was not accessible, so I had to recompile with llvm 8 using ef537f9. This version does not compile with llvm 12 though (not sure if it was to be expected).

Good news: I can confirm that the processing errors are gone. I will proceed testing.

**Comment by ruedbi** [comment] 2021-03-29 09:04
I have some more findings and will create a follow up ticket

**Comment by dougpuob** [comment] 2021-03-29 09:11
> Hi Douglas,
> 
> thanks for your bugfix, I highly appreciate that.
> The tag was not accessible, so I had to recompile with llvm 8 using [ef537f9](https://github.com/dougpuob/cppnamelint/commit/ef537f938892baddf87a7c47ef3274b6ccafa3cb). This version does not compile with llvm 12 though (not sure if it was to be expected).
> 
> Good news: I can confirm that the processing errors are gone. I will proceed testing.

Sounds great! Now you can't build with newer llvm with current CMakeLists.txt. I will update it later (#58 is the follow-up action item).

I created v0.3.4 for it.

**Comment by dougpuob** [comment] 2021-03-29 09:14
Close this issue, because I got the good feedback from @ruedbi .

> I have some more findings and will create a follow up ticket

Sure & thank you.

**Closed** 2021-03-29 09:14 UTC
